# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iplogmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
